language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: mCUqPqUtk6I4kc4nKDa+5xzRyychncF2vZ6SYpxGWMbj4dDVrPvmZSJfsCXoH0xiMnZZv/NXSR2rvtnVw9Zh7Zr0FWgcgaiXVSuVLzQA1mCxBKp2VsKKYOaLxUD5tpfbZvan82wAtwsH6QdRCUvE9n4VfRaTGggTFuIrbrKbiwTu/BPU6CfuZPHKibEdZrtRiAzfEsF5gInIyaM1CGJw+ciJNerrec0hRnc3VYD27s2hQbUYya/yImiVLi/Y/gF16edx5DPnQNVNn54VpETHmU04mfwym/9Jjm55J51FqmfwH6HdsZQLsIzYeSETjh1/Tx8Q2CO60aqPuVwMUhOmSQAf1GIqvezpX2DlcEONsNmyh6svoKWPWy4SrlGzPg9mh0ujNymf6lyxAuc8iUL0nKyTTFMJOVSa2lcvbf/3ZoKUk8M7X8t82qZKOKBCdf7IeogMooJHZz2g258WqyQU4GRyFR7r4JgaM59NJS04ebhuGCESUhGAIYJLk9LqL4slzLV8bRsjGFOJ7wDFIJ6nVdbqyLFgZ9HfsRu+QmzyFbeWQRlnNC+M8HtMwbXMQjPRp5IHtDEr72vIb1MJf9sj8cCIhIPfhrdUU9YCDx8F/9fXZvMF7fWbCLBUHHh5muYnUiL7Nyex5Yccaxcz3bub7rWOnSVV28NTZAIuvvdgolQ=
  app: nameless-dusk-12511
  on:
    repo: Yitzi2/node-shopping-list-integration-tests
